version: '3.9'

services:
  backend:
    build: ./backend_service
    container_name: backend
    env_file: ./backend_service/.env
    ports:
      - "3001:3001"
    networks:
      - monitoring
      
  frontend:
    build: ./frontend_service
    container_name: frontend
    env_file: ./frontend_service/.env
    networks:
      - monitoring

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/andrey-novaes.store/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/andrey-novaes.store/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - frontend
      - grafana
    networks:
      - monitoring

volumes:
  grafana-data:

networks:
  monitoring:
    driver: bridge
