global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3001']
      
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
      
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq_exporter:9419']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8081']
