global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3001']
      
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:80']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
