FROM node:18-slim AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:18-slim AS production

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/package*.json ./
COPY --from=build /app/wait-for-it.sh ./wait-for-it.sh

RUN npm ci --only=production

CMD ["sh", "-c", "./wait-for-it.sh rabbitmq:5672 --timeout=30 --strict & ./wait-for-it.sh postgres:5432 --timeout=30 --strict & wait && npm start"]
